telegram_token: "5676835648:AAE0rSJQaCklpS9fZUKq56wcwfyd7Ab8ymQ"
openai_api_key: ""
allowed_telegram_usernames: []  # if empty, the bot is available to anyone
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)